APPNAME := FINDMII
# Toolchain assumes devkitPro + WUT environment
CC := $(DEVKITPRO)/wut/bin/wut-cc

CFLAGS := -Wall -O2 -Iinclude -DWIIU
LDFLAGS := -Wl,-Map,$FINDMII.map

SRCS := src/main.c
OBJS := $(SRCS:.c=.o)

all: $FINDMII.rpx

$FINDMII.rpx: $(OBJS)
	$(CC) $(LDFLAGS) -o $@ $^
	@echo "Built $FINDMII.rpx"

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $FINDMII.rpx $FINDMII.map
