name: Build FINDMII

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install devkitPro pacman & Wii U toolchain (via .deb)
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg
        wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
        sudo dpkg -i devkitpro-pacman.deb || true
        sudo apt-get install -f -y
        sudo dkp-pacman -Syu --noconfirm
        sudo dkp-pacman -S --noconfirm wiiu-dev

    - name: Set environment variables
      run: |
        echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
        echo "DEVKITPPC=/opt/devkitpro/devkitPPC" >> $GITHUB_ENV
        echo "/opt/devkitpro/tools/bin" >> $GITHUB_PATH

    - name: Build with make
      run: make

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: FINDMII-rpx
        path: |
          FINDMII.rpx
          build/*.rpx
        overwrite: true
