   - name: Checkout codeAdd commentMore actions
      uses: actions/checkout@v3

    - name: Install devkitPro pacman & Wii U toolchain
      run: |
        curl -L https://apt.devkitpro.org/install-devkitpro-pacman.sh -o install.sh
        sudo bash install.sh



        sudo dkp-pacman -Syu --noconfirm
        sudo dkp-pacman -S --noconfirm wiiu-dev

    - name: Set environment variables
      run: |
        echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
        echo "DEVKITPPC=$DEVKITPRO/devkitPPC" >> $GITHUB_ENV
        echo "PATH=$PATH:$DEVKITPRO/tools/bin" >> $GITHUB_ENV

    - name: Build with make
      run: make
@@ -35,5 +38,5 @@ jobs:
        name: FINDMII-rpx
        path: |
          FINDMII.rpx
          *.rpx
        overwrite: true
