# .github/workflows/build.yml

name: Build FINDMII

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup devkitPro toolchains
      uses: boredazfcuk/setup-devkitpro@v5
      with:
        toolchains: wiiu   # installs devkitPPC + wut for Wii U

    - name: Build with make
      run: make

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: FINDMII-rpx
        path: |
          FINDMII.rpx
          build/*.rpx
        overwrite: true
